services:
  # web:
  #   image: node:20-alpine
  #   # restart: unless-stopped
  #   environment:
  #     - LNURL_DOMAIN=example.com
  #   working_dir: /home/node/app
  #   command: node index.js
  #   # user: node
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   volumes:
  #     - .:/home/node/app

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: dbpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 55432:5432

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  pgdata:
