services:
  # web:
  #   image: node:20-alpine
  #   # restart: unless-stopped
  #   environment:
  #     # - MONGO_USERNAME=$MONGO_USERNAME
  #     # - MONGO_PASSWORD=$MONGO_PASSWORD
  #     # - MONGO_HOSTNAME=db
  #     # - MONGO_PORT=$MONGO_PORT
  #     # - MONGO_DB=$MONGO_DB
  #     - LNURL_DOMAIN=example.com
  #   working_dir: /home/node/app
  #   command: node index.js
  #   # user: node
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   volumes:
  #     - .:/home/node/app

  db:
    image: mongo
    # restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    # restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@db:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - db
